### ISSUE TITLE
AttributeError: AWS::ElasticLoadBalancingV2::LoadBalancer object does not support attribute AccessLoggingPolicy

### ISSUE THREAD

**Issue by nethershaw** [cloudtools/troposphere#1031]
I am attempting to describe an Application Load Balancer (ELBv2) with an Access Logging Policy. Consider the following:

```
from troposphere import Template, Parameter, Ref, Tags, ImportValue
from troposphere.elasticloadbalancing import AccessLoggingPolicy
import troposphere.elasticloadbalancingv2 as elb

...

ALB = t.add_resource(elb.LoadBalancer(
    "ALB",
    Name="{0}-{1}-{2}".format(args.datacenter, args.cluster, args.version),
    Scheme="internet-facing",
    Subnets=[Ref(PublicSubnet1), Ref(PublicSubnet2), Ref(PublicSubnet3)],
    SecurityGroups=[Ref(SecurityGroupDefault), Ref(SecurityGroupELB)],
    AccessLoggingPolicy=AccessLoggingPolicy(
        EmitInterval="5",
        Enabled=True,
        S3BucketName=ImportValue("delivery-S3-{0}-bucket".format(args.region)),
        S3BucketPrefix="{0}-{1}-{2}".format(args.datacenter, args.cluster, args.version)
    )
))
```

This generates an exception (the references to Ansible indicate that it is the caller of my Troposphere template rendering script):

```
Traceback (most recent call last):
  File "/home/mavaug/.ansible/tmp/ansible-tmp-1524758100.1131444-81078121464197/rendertemplate-dserver.py", line 288, in <module>
    S3BucketPrefix="{0}-{1}-{2}".format(args.datacenter, args.cluster, args.version)
  File "/home/mavaug/.local/lib64/python3.5/site-packages/troposphere/__init__.py", line 126, in __init__
    self.__setattr__(k, v)
  File "/home/mavaug/.local/lib64/python3.5/site-packages/troposphere/__init__.py", line 214, in __setattr__
    (type_name, name))
AttributeError: AWS::ElasticLoadBalancingV2::LoadBalancer object does not support attribute AccessLoggingPolicy
```

Indeed, on inspection of [troposphere/elasticloadbalancingv2.py](../blob/master/troposphere/elasticloadbalancingv2.py), I see no such property in the LoadBalancer class. Is this intentional? I see no other way to add an Access Logging Policy to a second-generation Load Balancer, though it is described here in the CFN docs:

https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-ec2-elb-accessloggingpolicy.html

Thank you.

**Comment by NIXKnight** [comment]
Can anyone provide an example on how to use `LoadBalancerAttributes`?

**Comment by rajatrj16** [comment]
Can you please add an example of adding `AccessLoggingPolicy` and `DeletionProtection` in `LoadBalancerAttributes`

I tried this way, But it fails---

```
LoadBalancerAttributes=[elb.LoadBalancerAttributes(
             DeletionPolicy=True,
```
Please add some basic example of defining protperty in `LoadBalancerAttributes` for `elasticloadbalancingv2`

**Comment by rajatrj16** [comment]
So after lots of searching i find Enabling `DeletionProtection` 
LoadBalancerAttributes=[elb.LoadBalancerAttributes(
            Key='deletion_protection.enabled',Value='true'
        )]

But still need to work on `AccessLogging`

**Comment by markpeek** [comment]
Perhaps adding additional LoadBalancerAttributes using this [documentation](https://docs.aws.amazon.com/elasticloadbalancing/latest/application/application-load-balancers.html#load-balancer-attributes) or [this](https://docs.aws.amazon.com/elasticloadbalancing/latest/APIReference/API_LoadBalancerAttribute.html) to get the proper keys?
