### ISSUE TITLE
ScheduleExpression validator doesn't validate examples provided by AWS

### ISSUE THREAD

**Issue by flou** [cloudtools/troposphere#1139]
The following schedule expressions should pass validation (taken from [AWS docs](https://docs.aws.amazon.com/AmazonCloudWatch/latest/events/ScheduledEvents.html#CronExpressions)) but they raise errors upon validation with `event_schedule_expression`:
```
cron(15 10 ? * 6L 2002-2005)
cron(*/7 5-10 5 * *)
cron(5,35 14 * * ? *)
cron(0 18 ? * MON-FRI *)
cron(0/15 * * * ? *)
cron(0/10 * ? * MON-FRI *)
cron(0/5 8-17 ? * MON-FRI *)
```

```
>>> from troposphere.validators import event_schedule_expression

>>> event_schedule_expression("cron(15 10 ? * 6L 2002-2005)")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "troposphere/validators.py", line 375, in event_schedule_expression
    % expression
ValueError: The following is not a valid expression: "cron(15 10 ? * 6L 2002-2005)"

>>> event_schedule_expression("cron(0/15 * * * ? *)")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "troposphere/validators.py", line 375, in event_schedule_expression
    % expression
ValueError: The following is not a valid expression: "cron(0/15 * * * ? *)"

>>> event_schedule_expression("cron(0/5 8-17 ? * MON-FRI *)")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "troposphere/validators.py", line 375, in event_schedule_expression
    % expression
ValueError: The following is not a valid expression: "cron(0/5 8-17 ? * MON-FRI *)"
```

**Comment by jonikarppinen** [comment]
Yes. This got broken in 2.3.2 and this change is the culprit: https://github.com/cloudtools/troposphere/pull/1114

As quick fix, use [troposphere 2.3.1](https://github.com/cloudtools/troposphere/pull/1114#issuecomment-418673853) instead of the latest version.

**Comment by markpeek** [comment]
I looked into fixing the regex's last night but the changes were pretty large and would need more scrutiny/testing. I just backed out #1114 and released [troposphere 2.3.3](https://github.com/cloudtools/troposphere/releases/tag/2.3.3).

**Comment by ChristopherHackett** [comment]
The approach I used in #1114 was mostly regex driven but maybe instead the cron string should just get tokenised by regex and each field of the cron handled individually. Tests can be updated to have the right use of `-` , `,` and `/` and (or alternately just reflect the documented examples).
