### ISSUE TITLE
Getting numerous errors in cfn2py script

### ISSUE THREAD

**Issue by efreedom79** [cloudtools/troposphere#115]
Would there be value in loading my json here and letting someone work through specific issues? Is there currently working going on with cfn2py ?

Here's the first error from running the script on the json file:
```
from troposphere.route53 import RecordSetGroup
from troposphere.elasticloadbalancing import LoadBalancer
from troposphere.cloudwatch import Alarm
from troposphere.ec2 import SecurityGroup
from troposphere.autoscaling import LaunchConfiguration
from troposphere.autoscaling import AutoScalingGroup

t = Template()

t.add_version("2010-09-09")

t.add_description("""\
experts-dev2-experts - Shows experts and their topics""")
devexpertsELBDNSARecord0 = t.add_resource(RecordSetGroup(
    "devexpertsELBDNSARecord0",
    HostedZoneName="inpwrd.net.",
    Comment="Alias targeted to devexpertsELB ELB.",
Traceback (most recent call last):
  File "/usr/bin/cfn2py", line 229, in <module>
    globals()["do_" + s.lower()](d)
  File "/usr/bin/cfn2py", line 128, in do_resources
    print '    %s=%s,' % (pk, output_value(pv))
  File "/usr/bin/cfn2py", line 178, in output_value
    return "[" + ", ".join(out) + "]"
TypeError: sequence item 0: expected string, NoneType found
```

**Comment by BardiaAfshin** [comment]
@efreedom79 can you share how you implemented the usage of AliasTarget within your troposphere usage?

I see it referenced in the JSON, but not any python code. Also, please format your code with the proper mark down delimiters.
