### ISSUE TITLE
Tags of mixed type cannot be used on python 3

### ISSUE THREAD

**Issue by troyready** [cloudtools/troposphere#1161]
```
troyready $ python3
Python 3.6.6 (default, Sep 12 2018, 18:26:19) 
[GCC 8.0.1 20180414 (experimental) [trunk revision 259383]] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from troposphere import Sub, Tags
>>> Tags({Sub('mystringtosub'): 'val', 'foo': 'bar'}).to_dict()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/troyready/.local/lib/python3.6/site-packages/troposphere/__init__.py", line 534, in __init__
    for k, v in sorted(tag_dict.items()):
TypeError: '<' not supported between instances of 'str' and 'Sub'
```
This works properly still on python 2:
```
troyready $ python
Python 2.7.15rc1 (default, Apr 15 2018, 21:51:34) 
[GCC 7.3.0] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> from troposphere import Sub, Tags
>>> Tags({Sub('mystringtosub'): 'val', 'foo': 'bar'}).to_dict()
[{'Key': {'Fn::Sub': 'mystringtosub'}, 'Value': 'val'}, {'Key': 'foo', 'Value': 'bar'}]

```

**Comment by markpeek** [comment]
Sorry for the delay in responding to this issue. I'm thinking a check to sort only if all the keys are strings. Alternatively pull out all the non-string keys and sort the remaining. Thoughts?
