### ISSUE TITLE
TemplateGenerator fail to parse template Fn::Sub with variable map

### ISSUE THREAD

**Issue by JPLemelin** [cloudtools/troposphere#1174]
I trying to load a SAM template generated from chalice and I encounter this error. I simplify the template as much as possible.

```json
{
  "AWSTemplateFormatVersion": "2010-09-09",
  "Resources": {
    "MySNS":{
      "Type" : "AWS::SNS::Topic",
      "Properties" : {
        "DisplayName" : "Display Name",
        "TopicName" : {
          "Fn::Sub": [ "MySNS-Test-${ABC}",
            {
              "ABC": "abc"
            }
          ]
        }
      }
    }
  }
}
``` 

Simple script to reproduce the issue
```python
import json
from troposphere.template_generator import TemplateGenerator

with open("sns.json", 'r') as f:
    json_data = json.loads(f.read())
template = TemplateGenerator(json_data)
```

Console output
```
>python sample.py
Traceback (most recent call last):
  File "/Users/lemjean/Unicorn/xxxxxxxxxx/.venv2/lib/python3.6/site-packages/troposphere/template_generator.py", line 227, in _create_instance
    return cls(*self._convert_definition(args))
TypeError: __init__() takes 2 positional arguments but 3 were given

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "sample.py", line 7, in <module>
    template = TemplateGenerator(json_data)
  File "/Users/lemjean/Unicorn/xxxxxxxxxx/.venv2/lib/python3.6/site-packages/troposphere/template_generator.py", line 63, in __init__
    self._get_resource_type_cls(v)
  File "/Users/lemjean/Unicorn/xxxxxxxxxx/.venv2/lib/python3.6/site-packages/troposphere/template_generator.py", line 162, in _convert_definition
    return self._create_instance(expected_type, args, ref)
  File "/Users/lemjean/Unicorn/xxxxxxxxxx/.venv2/lib/python3.6/site-packages/troposphere/template_generator.py", line 268, in _create_instance
    kwargs[prop_name], prop_name)
  File "/Users/lemjean/Unicorn/xxxxxxxxxx/.venv2/lib/python3.6/site-packages/troposphere/template_generator.py", line 169, in _convert_definition
    function_type, list(definition.values())[0])
  File "/Users/lemjean/Unicorn/xxxxxxxxxx/.venv2/lib/python3.6/site-packages/troposphere/template_generator.py", line 243, in _create_instance
    if '__init__() takes exactly' not in ex.message:
AttributeError: 'TypeError' object has no attribute 'message'
```

More information about my env:
* python 3.6.5
* troposhere installed with `pip install troposphere[policy]`
  * awacs==0.8.1
  * cfn-flip==1.0.3
  * Click==7.0
  * PyYAML==3.13
  * six==1.11.0
  * troposphere==2.3.3

**Comment by JPLemelin** [comment]
The issue can from the definition of function `Sub`

As define here:
https://github.com/cloudtools/troposphere/blob/91dc3b5f8916b96ead45783c58d24ce7305c1701/troposphere/__init__.py#L474-L478

When the function is call **from the TemplateGenerator**, it will always have one or two arguments, never more, and if the second argument are present, it will be a **dict** (and it's dict are not unpackaged)

exemple:
```
Sub('MySNS-Test-${ABC}-${DEF}', { 'ABC': 'abc', 'DEF': 'def' })
```

When the function is call from the unit-tests, the second argument are **unpackaged**

https://github.com/cloudtools/troposphere/blob/91dc3b5f8916b96ead45783c58d24ce7305c1701/tests/test_basic.py#L406-L423

This is equivalent of:
```
Sub('MySNS-Test-${ABC}-${DEF}', ABC='abc', DEF='def')
```

So, how should we fix it ?

If we change Sub to
```
def __init__(self, input_str, *values): 
```
the template generator will work fine, but we will have a **broking change**!

We can also supporte both of them with more code:
```python
class Sub(AWSHelperFn):
    def __init__(self, input_str, dict_values=None, **values):
        # merge dict
        if dict_values:
            values.update(dict_values)
        self.data = {'Fn::Sub': [input_str, values] if values else input_str}
```
 
Any suggest ? Any comment ?

PS: I will open a PR!
