### ISSUE TITLE
Type error

### ISSUE THREAD

**Issue by basneve** [cloudtools/troposphere#1414]
Used the cfn2py script and the resulting script gives me the follwing TypeError:

setup-cloudfront.py:15: DeprecationWarning: The add_version() method is deprecated, please switch to using set_version() instead.

  t.add_version("2010-09-09")
Traceback (most recent call last):
  File "setup-cloudfront.py", line 29, in <module>
    ForwardedValues={ "QueryString": True, "Cookies": { "Forward": "none" } },
  File "C:\Users\bas\AppData\Local\Programs\Python\Python37\lib\site-packages\troposphere\__init__.py", line 354, in __init__
    super(AWSProperty, self).__init__(title, **kwargs)
  File "C:\Users\bas\AppData\Local\Programs\Python\Python37\lib\site-packages\troposphere\__init__.py", line 127, in __init__
    self.__setattr__(k, v)
  File "C:\Users\bas\AppData\Local\Programs\Python\Python37\lib\site-packages\troposphere\__init__.py", line 214, in __setattr__
    self._raise_type(name, value, expected_type)
  File "C:\Users\bas\AppData\Local\Programs\Python\Python37\lib\site-packages\troposphere\__init__.py", line 232, in _raise_type
    expected_type))
TypeError: <class 'troposphere.cloudfront.DefaultCacheBehavior'>: None.ForwardedValues is <class 'dict'>, expected <class 'troposphere.cloudfront.ForwardedValues'>

Howto proceed ?

**Comment by basneve** [comment]
Duplicate of #1367
