### ISSUE TITLE
"AttributeError: AWS::EC2::EIP object does not support attribute Tags." -- But it should.

### ISSUE THREAD

**Issue by bwdbethke** [cloudtools/troposphere#1672]
AWS::EC2::EIP should support tags according to https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-ec2-eip.html
```
Tags
Any tags assigned to the Elastic IP address.
Required: No
Type: List of Tag
```
however I'm getting this error when I try:
> AttributeError: AWS::EC2::EIP object does not support attribute Tags

I see tags mentioned in the class EIP
```
class EIP(AWSObject):
    resource_type = "AWS::EC2::EIP"

    props = {
        'InstanceId': (basestring, False),
        'Domain': (basestring, False),
        'PublicIpv4Pool': (basestring, False),
        'Tags': (Tags, False),
    }
```
but elsewhere in the file lists of tags are done like: 
```
'Tags': ((Tags, list), False),
```

**Comment by markpeek** [comment]
Try something like this?
```
$ cat eip.py
from troposphere import Tags, Template
from troposphere.ec2 import EIP

t = Template()
t.add_resource(EIP("sampleeip", Tags=Tags(foo='foo')))
print(t.to_json())


$ python eip.py
{
    "Resources": {
        "sampleeip": {
            "Properties": {
                "Tags": [
                    {
                        "Key": "foo",
                        "Value": "foo"
                    }
                ]
            },
            "Type": "AWS::EC2::EIP"
        }
    }
}
```

**Comment by bwdbethke** [comment]
Ok i'll try.

eip.py:
```
from troposphere import Tags, Template
from troposphere.ec2 import EIP

t = Template()
t.add_resource(EIP("sampleeip", Tags=Tags(foo='foo')))
print(t.to_json())
```

$ python eip.py
```
python eip.py
Traceback (most recent call last):
  File "eip.py", line 5, in <module>
    t.add_resource(EIP("sampleeip", Tags=Tags(foo='foo')))
  File "C:\Users\bwdbethke\.virtualenvs\sceptre-BLAHBLAH\lib\site-packages\troposphere\__init__.py", line 127, in __init__
    self.__setattr__(k, v)
  File "C:\Users\bwdbethke\.virtualenvs\sceptre-BLAHBLAH\lib\site-packages\troposphere\__init__.py", line 225, in __setattr__
    (type_name, name))
AttributeError: AWS::EC2::EIP object does not support attribute Tags
```

FWIW, it looks like my environment has troposphere 2.5.2 installed

**Comment by markpeek** [comment]
Ahhh, you will need at least 2.5.3 since it was added into that release.

**Comment by bwdbethke** [comment]
Ahhh.
I didn't notice anything _specifically_ about EIP tagging in the change notes, but it is probably in there rolled up under something else. I should have checked the class EIP in my version (2.5.2) vs later ones.

**Comment by bwdbethke** [comment]
Yep. I don't see the Tags attribute in 2.5.2 but I do see it is there in 2.5.3 and later.
I'll update my troposphere and this issue can be closed.
