### ISSUE TITLE
cloudfront.StatusCodes raises TypeError

### ISSUE THREAD

**Issue by nielslaukens** [cloudtools/troposphere#1730]
Hello,

First of all, thank you for all your effort and love you put in to this project. I enjoy troposphere on a daily basis. Keep up the good work!

I believe I've found a bug with the [recently added code for CloudFront Origin Groups](https://github.com/cloudtools/troposphere/commit/f0c6c7be8963de2ad3537b1864b62b02a7b486fc). (Or, with some other code that this new code is interacting with, of course). Steps to reproduce:

```python
from troposphere import cloudfront
cloudfront.StatusCodes(Quantity=1, Items=[503])
```

This raises the following TypeError (paths stripped for privacy):

```
Traceback (most recent call last):
  File "<stdin>", line 3, in <module>
  File ".../troposphere/__init__.py", line 354, in __init__
    super(AWSProperty, self).__init__(title, **kwargs)
  File ".../troposphere/__init__.py", line 127, in __init__
    self.__setattr__(k, v)
  File ".../troposphere/__init__.py", line 202, in __setattr__
    if not isinstance(v, tuple(expected_type)) \
TypeError: isinstance() arg 2 must be a class, type, or tuple of classes and types
```

I'll give it a try to fix this myself and follow up with a Pull Request if I manage to actually fix it, but I wanted to report this already.

<details>
<summary>Version info</summary>

```
$ python -V
Python 3.7.7

$ pip list
Package     Version
----------- -------
cfn-flip    1.2.3
click       7.1.2
pip         19.2.3
PyYAML      5.3.1
setuptools  41.2.0
six         1.15.0
troposphere 2.6.1
```

Running on macOS 10.15.5
</details>

**Comment by nielslaukens** [comment]
This seems to be already fixed in master by 316efc08b0f6364b2c740b66f31ed34ff9e219bc. However, this commit is not yet released.
