### ISSUE TITLE
Unable to create Athena Workgroup

### ISSUE THREAD

**Issue by RamdevWudaliTR** [cloudtools/troposphere#1734]
With the release of 2.6.1, the ability to create Athena Workgroups was added. However, after upgrading to this release, I am unable to create the corresponding CF template for an Athena Workgroup. 
Whenever I use sceptre to generate the template, I get the following error stack : 

```
(cicd-lap) $ sceptre generate labs-preprod/test-workspace >| test_wksp14.json
[2020-06-29 17:15:19] - testTrop.py:23:  Template error in 'sceptre_handler'
=> `ws = AthenaWGrp(sceptre_user_data)`
[2020-06-29 17:15:19] - testTrop.py:13:  Template error in '__init__'
=> `self.create_template()`
[2020-06-29 17:15:19] - testTrop.py:16:  Template error in 'create_template'
=> `athena_workgroup=self.template.add_resource(WorkGroup(`
Traceback (most recent call last):
  File "/usr/local/anaconda3/envs/cicd-lap/bin/sceptre", line 8, in <module>
    sys.exit(cli())
  File "/usr/local/anaconda3/envs/cicd-lap/lib/python3.6/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/anaconda3/envs/cicd-lap/lib/python3.6/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/usr/local/anaconda3/envs/cicd-lap/lib/python3.6/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/anaconda3/envs/cicd-lap/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/anaconda3/envs/cicd-lap/lib/python3.6/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/anaconda3/envs/cicd-lap/lib/python3.6/site-packages/click/decorators.py", line 21, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/local/anaconda3/envs/cicd-lap/lib/python3.6/site-packages/sceptre/cli/helpers.py", line 36, in decorated
    return func(*args, **kwargs)
  File "/usr/local/anaconda3/envs/cicd-lap/lib/python3.6/site-packages/sceptre/cli/template.py", line 65, in generate_command
    responses = plan.generate()
  File "/usr/local/anaconda3/envs/cicd-lap/lib/python3.6/site-packages/sceptre/plan/plan.py", line 348, in generate
    return self._execute(*args)
  File "/usr/local/anaconda3/envs/cicd-lap/lib/python3.6/site-packages/sceptre/plan/plan.py", line 40, in _execute
    return executor.execute(*args)
  File "/usr/local/anaconda3/envs/cicd-lap/lib/python3.6/site-packages/sceptre/plan/executor.py", line 55, in execute
    stack, status = future.result()
  File "/usr/local/anaconda3/envs/cicd-lap/lib/python3.6/concurrent/futures/_base.py", line 425, in result
    return self.__get_result()
  File "/usr/local/anaconda3/envs/cicd-lap/lib/python3.6/concurrent/futures/_base.py", line 384, in __get_result
    raise self._exception
  File "/usr/local/anaconda3/envs/cicd-lap/lib/python3.6/concurrent/futures/thread.py", line 56, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/anaconda3/envs/cicd-lap/lib/python3.6/site-packages/sceptre/plan/executor.py", line 62, in _execute
    result = getattr(actions, self.command)(*args)
  File "/usr/local/anaconda3/envs/cicd-lap/lib/python3.6/site-packages/sceptre/plan/actions.py", line 568, in generate
    return self.stack.template.body
  File "/usr/local/anaconda3/envs/cicd-lap/lib/python3.6/site-packages/sceptre/template.py", line 137, in body
    raise e
  File "/usr/local/anaconda3/envs/cicd-lap/lib/python3.6/site-packages/sceptre/template.py", line 127, in body
    self._body = self._call_sceptre_handler()
  File "/usr/local/anaconda3/envs/cicd-lap/lib/python3.6/site-packages/sceptre/template.py", line 175, in _call_sceptre_handler
    body = module.sceptre_handler(self.sceptre_user_data)
  File "/Users/u0102180/Code/scw/aws-github/c3-secure-content-workspace_cicd/templates/testTrop.py", line 23, in sceptre_handler
    ws = AthenaWGrp(sceptre_user_data)
  File "/Users/u0102180/Code/scw/aws-github/c3-secure-content-workspace_cicd/templates/testTrop.py", line 13, in __init__
    self.create_template()
  File "/Users/u0102180/Code/scw/aws-github/c3-secure-content-workspace_cicd/templates/testTrop.py", line 16, in create_template
    athena_workgroup=self.template.add_resource(WorkGroup(
TypeError: __init__() missing 1 required positional argument: 'title'
```

The code is as follows : 

```
from troposphere import Tags, Parameter, Template, Sub, Join, Ref, Base64
from troposphere import Output, Export, GetAtt, ImportValue
from troposphere.athena import WorkGroup, WorkGroupConfiguration, ResultConfiguration, WorkGroupConfigurationUpdates
from troposphere.athena import ResultConfigurationUpdates, EncryptionConfiguration


class AthenaWGrp(object):
    """Sceptre & Troposphere template to a workspace."""
    def __init__(self, sceptre_user_data):
        """Setup template."""
        self.template = Template()
        self.sceptre_user_data = sceptre_user_data
        self.create_template()

    def create_template(self):
        athena_workgroup=self.template.add_resource(WorkGroup(
        ))
        


def sceptre_handler(sceptre_user_data):
    """Method required for Sceptre."""
    ws = AthenaWGrp(sceptre_user_data)
    return ws.template.to_json()
```
`

**Comment by markpeek** [comment]
It's a bit hard to read and duplicate due to the formatting of this issue. But it appears the error is:
```
line 16, in create_template athena_workgroup=self.template.add_resource(WorkGroup( TypeError: __init__() missing 1 required positional argument: 'title'
```
This is a common issue where you need to provide the json/yaml name for the resource as a "title" such as this:
```
athena_workgroup=self.template.add_resource("myathenaworkgroup", WorkGroup())
```
Note the addition of "myathenaworkgroup". Of course there may be additional issues where WorkGroup() has required fields you need to pass in.

**Comment by RamdevWudaliTR** [comment]
@markpeek, I have the same error even after adding "title" prior to the call to WorkGroup() 

```
   def create_template(self):
        athena_workgroup=self.template.add_resource("myathenaworkgroup", WorkGroup(
        ))

```

**Comment by markpeek** [comment]
Doh! That will teach me to type up a quick code sample into github...

**Comment by markpeek** [comment]
```

**Comment by markpeek** [comment]
```
>>> from troposphere import Template
>>> from troposphere.athena import WorkGroup
>>> t = Template()
>>> t.add_resource(WorkGroup("myathenaworkgroup"))
<troposphere.athena.WorkGroup object at 0x1053ed990>
```

**Comment by RamdevWudaliTR** [comment]
@markpeek  Thanks,  I had to specify the keyword title and then specify a value. Not sure why its specifically needed for Athena WorkGroups. It does not seem like its required for other resources. (atleast not the title keyword ). If it is specified as a mandatory parameter it would help, perhaps I am missing something. 

the following code worked for me : 

```
from troposphere import Tags, Parameter, Template, Sub, Join, Ref, Base64
from troposphere import Output, Export, GetAtt, ImportValue
from troposphere.athena import WorkGroup, WorkGroupConfiguration, ResultConfiguration, WorkGroupConfigurationUpdates
from troposphere.athena import ResultConfigurationUpdates, EncryptionConfiguration


class AthenaWGrp(object):
    """Sceptre & Troposphere template to a workspace."""
    def __init__(self, sceptre_user_data):
        """Setup template."""
        self.template = Template()
        self.sceptre_user_data = sceptre_user_data
        self.create_template()

    def create_template(self):
        athena_workgroup=self.template.add_resource(WorkGroup(
            title="myathenaworkgroup",
            Description="Athena group for Workspace configuration",
            Name="AtWrkGrp",
        ))
        


def sceptre_handler(sceptre_user_data):
    """Method required for Sceptre."""
    ws = AthenaWGrp(sceptre_user_data)
    return ws.template.to_json()
```
