### ISSUE TITLE
Basestring causing error 

### ISSUE THREAD

**Issue by Yaronn44** [cloudtools/troposphere#1951]
``I'm actually using the library [zappa](https://github.com/zappa/Zappa) to maintain and update some Lambdas.
Everything was working great 5 days ago, but I discovered this morning that I can't update my Lambdas anymore because of this error when I do a `zappa update x`:
```
Traceback (most recent call last):
  File "/home/runner/work/api/venv/bin/zappa", line 5, in <module>
    from zappa.cli import handle
  File "/home/runner/work/api/venv/lib/python3.7/site-packages/zappa/cli.py", line 43, in <module>
    from .core import API_GATEWAY_REGIONS, Zappa, logger
  File "/home/runner/work/api/venv/lib/python3.7/site-packages/zappa/core.py", line 31, in <module>
    import troposphere
  File "/home/runner/work/api/venv/lib/python3.7/site-packages/troposphere/__init__.py", line 586, in <module>
    class Template(object):
  File "/home/runner/work/api/venv/lib/python3.7/site-packages/troposphere/__init__.py", line 588, in Template
    'AWSTemplateFormatVersion': (basestring, False),
NameError: name 'basestring' is not defined
```

Absolutly nothing has change in my CI and my dependencies didn't changed either. I'm really struggling on this, and even if I know the problem may not come from troposphere itself, i wanted to now if somebody has encounter it ?

My CI runs with Ubuntu 18.04, uses Python 3.7.9, and the troposphere version is 2.7.1 (it's impossible to update to a newer version as Zappa doesn't handle it). I check and double check those dependencies by printing the versions of troposphere and Python just before doing the `zappa update x` in my CI.

When I install tropospher on my computer, which is running on Windows 10, with Python 3.7.9, all of the `basestring` are automatically replace with `str`. I don't understand very well how is this happening, and I would be glad if someone **could enlighten me about this**.
I'm felling like the problem is coming from this behavior. The `basestring` were all replace automatically in my CI at libraries installation, and it stop doing it recently.

**Comment by Yaronn44** [comment]
So it was a setuptools problem... Sorry for the useless issue
