### ISSUE TITLE
Getting error when I try to use AWS::EC2::KeyPair::KeyName as parameter type

### ISSUE THREAD

**Issue by sreekanthpulagam** [cloudtools/troposphere#381]
StackTrace:

Traceback (most recent call last):
  File "/home/sreekanth/font/sample.py", line 246, in <module>
    print(t.to_json())
  File "/home/sreekanth/.local/lib/python2.7/site-packages/troposphere/__init__.py", line 455, in to_json
    sort_keys=sort_keys, separators=separators)
  File "/usr/lib/python2.7/json/__init__.py", line 250, in dumps
    sort_keys=sort_keys, **kw).encode(obj)
  File "/usr/lib/python2.7/json/encoder.py", line 209, in encode
    chunks = list(chunks)
  File "/usr/lib/python2.7/json/encoder.py", line 434, in _iterencode
    for chunk in _iterencode_dict(o, _current_indent_level):
  File "/usr/lib/python2.7/json/encoder.py", line 408, in _iterencode_dict
    for chunk in chunks:
  File "/usr/lib/python2.7/json/encoder.py", line 408, in _iterencode_dict
    for chunk in chunks:
  File "/usr/lib/python2.7/json/encoder.py", line 442, in _iterencode
    o = _default(o)
  File "/home/sreekanth/.local/lib/python2.7/site-packages/troposphere/__init__.py", line 352, in default
    return obj.JSONrepr()
  File "/home/sreekanth/.local/lib/python2.7/site-packages/troposphere/__init__.py", line 162, in JSONrepr
    self.validate()
  File "/home/sreekanth/.local/lib/python2.7/site-packages/troposphere/__init__.py", line 490, in validate
    "the String type." % p)
ValueError: AllowedPattern can only be used with parameters of the String type.

**Comment by sreekanthpulagam** [comment]
Unfortunately I was using MaxLength="255" in keyname parameter
like below

KeyName = t.add_parameter(Parameter(
    "KeyName",
    Type="AWS::EC2::KeyPair::KeyName",
    Description="Name of an existing EC2 KeyPair to enable SSH access",
    MaxLength="255",
    ConstraintDescription="can contain only ASCII characters.",
))

Probably I should remove this
Later I found there is a check for validity by debugging code.
