### ISSUE TITLE
Validation of AutoScalingGroup with UpdatePolicy fails when maxSize is an expression

### ISSUE THREAD

**Issue by ubergeek42** [cloudtools/troposphere#445]
Troposphere version: `troposphere==1.5.0`
Snippet example:
```
t.add_resource(AutoScalingGroup(
        "WebserverAutoScalingGroup",
        AvailabilityZones=GetAZs(Ref("AWS::Region")),
        LaunchConfigurationName=Ref(r['webserver_lc']),
        LoadBalancerNames=[Ref(r['webserver_elb'])],

        UpdatePolicy=UpdatePolicy(
            AutoScalingRollingUpdate=AutoScalingRollingUpdate(
                PauseTime='PT5M',
                MinInstancesInService="1",
                MaxBatchSize='1',
                WaitOnResourceSignals=True
            )
        ),
        CreationPolicy=CreationPolicy(
            ResourceSignal=ResourceSignal(
                Timeout='PT15M'
            )
        ),
        HealthCheckGracePeriod=300,
        HealthCheckType="EC2",

        DesiredCapacity=If(
            "IsStaging",
            '1',
            '3',
        ),
        MinSize=If(
            "IsStaging",
            '1',
            '3'
        ),
        MaxSize=If(
            "IsStaging",
            '1',
            '5'
        )
    ))
```

This gives the error:
```
Traceback (most recent call last):
<-- snip -->
packages/troposphere/__init__.py", line 367, in default
    return obj.JSONrepr()
  File "venv/lib/python2.7/site-packages/troposphere/__init__.py", line 176, in JSONrepr
    self.validate()
  File "venv/lib/python2.7/site-packages/troposphere/autoscaling.py", line 147, in validate
    maxCount = int(self.MaxSize)
TypeError: int() argument must be a string or a number, not 'If'
```

Let me know if you need any other details.

**Comment by ubergeek42** [comment]
I added a simple PR that fixes this for me. See #446
