### ISSUE TITLE
Deepcopying resources causes infinite recursion.

### ISSUE THREAD

**Issue by Varriount** [cloudtools/troposphere#648]
Currently, deepcopying any troposphere resource object triggers an infinite recursion:

```
>>> from troposphere.ec2 import SecurityGroup
>>> from copy import deepcopy
>>> group = SecurityGroup(
...   'SomeSecurityGroup',
...   VpcId = '',
...   GroupDescription = "A security group."
... )
>>> deepcopy(group)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/.../lib/python3.5/copy.py", line 182, in deepcopy
    y = _reconstruct(x, rv, 1, memo)
  File "/.../lib/python3.5/copy.py", line 298, in _reconstruct
    if hasattr(y, '__setstate__'):
  File "/.../lib/python3.5/site-packages/troposphere/__init__.py", line 86, in __getattr__
    return self.properties.__getitem__(name)
  File "/.../lib/python3.5/site-packages/troposphere/__init__.py", line 86, in __getattr__
    return self.properties.__getitem__(name)
<...>
  File "/.../lib/python3.5/site-packages/troposphere/__init__.py", line 86, in __getattr__
    return self.properties.__getitem__(name)
RecursionError: maximum recursion depth exceeded while calling a Python object
```

I was able to work around this by assigning a deepcopy method to the BaseAWSObject:
```
def __deepcopy__(self, memo):
    memo[id(self)] = self
    return self
BaseAWSObject.__deepcopy__ = __deepcopy__
```

However this just disables deepcopying of any resources (which for my needs was enough). If I could be given some hint as to what exactly is causing the recursion, I'd be willing to write up a patch and pull request. At present I'm not familiar enough with Troposphere's internals to provide a more concrete fix.

**Comment by markpeek** [comment]
Very odd, I ran your code and did not get the recursion error.
```
>>> from troposphere.ec2 import SecurityGroup
>>> from copy import deepcopy
>>> group = SecurityGroup('SomeSecurityGroup', VpcId = '', GroupDescription = "A security group.")
>>> deepcopy(group)
<troposphere.ec2.SecurityGroup object at 0x1057f8c10>
```
Are you running the latest troposphere version or some older version? And I'm using Python 2.7.12.
```
>>> import troposphere; troposphere.__version__
'1.9.1'
```
I'd like to repro to make sure we are seeing the same issue. To answer your question, you're probably seeing an issue with the BaseAWSObject overrides of \_\_getattr\_\_ and \_\_setattr\_\_ which deepcopy calls to make the copies.

**Comment by Varriount** [comment]
Ah, I should have mentioned, I'm running Python 3.6.

**Comment by markpeek** [comment]
Not sure I like this [change](https://github.com/cloudtools/troposphere/commit/e7b8ab075af008777a44d49f186a15005d247b29) so it is on a branch but it appears to make deepcopy work in Python 3.6.
