### ISSUE TITLE
ElastiCache.SubnetGroup cannot set CacheSubnetGroupName

### ISSUE THREAD

**Issue by vivricanopy** [cloudtools/troposphere#664]
Example:
```
elasticache.SubnetGroup(
    "ElasticacheMemcSubnetGroup",
    CacheSubnetGroupName="somename",
    Description='Elasticache Subnet group for private access',
    SubnetIds=["subnet-12345"]
)
```

Output:
```
Traceback (most recent call last):
  File "~/mytroposphere.py", line 271, in <module>
    SubnetIds=["subnet-12345"],
  File "/usr/local/lib/python2.7/site-packages/troposphere/__init__.py", line 78, in __init__
    self.__setattr__(k, v)
  File "/usr/local/lib/python2.7/site-packages/troposphere/__init__.py", line 159, in __setattr__
    (type_name, name))
AttributeError: AWS::ElastiCache::SubnetGroup object does not support attribute CacheSubnetGroupName
```

**Comment by horacio3** [comment]
Seems to work currently. I am using the newest release of troposphere.
```
from troposphere import elasticache, Template

t = Template()

t.add_resource(elasticache.SubnetGroup(
    "ElasticacheMemcSubnetGroup",
    CacheSubnetGroupName="somename",
    Description='Elasticache Subnet group for private access',
    SubnetIds=["subnet-12345"]
))

print(t.to_json())
```

**Comment by markpeek** [comment]
@horacio3 you're correct. This was added in 1.9.0 released on 2016-11-15.

**Comment by vivricanopy** [comment]
Ah, thank you @horacio3 @markpeek! I was using 1.8.2
