### ISSUE TITLE
TypeError when using elasticloadbalancingv2.TargetGroupAttribute

### ISSUE THREAD

**Issue by gkrizek** [cloudtools/troposphere#680]
When trying to use `elasticloadbalancingv2.TargetGroupAttribute` with `elasticloadbalancingv2.TargetGroupAttributes` it fails with a TypeError that it was expecting exactly what I'm using. I really tried to dig into what I was doing wrong, but I can't see how I'm using it incorrectly.

My Error:

```
Traceback (most recent call last):
  File "troposphere/es.nodesource.io.cf.py", line 204, in <module>
    Value="10"
  File "/usr/local/lib/python2.7/site-packages/troposphere/__init__.py", line 106, in __init__
    self.__setattr__(k, v)
  File "/usr/local/lib/python2.7/site-packages/troposphere/__init__.py", line 159, in __setattr__
    self._raise_type(name, value, expected_type)
  File "/usr/local/lib/python2.7/site-packages/troposphere/__init__.py", line 194, in _raise_type
    expected_type))
TypeError: <class 'troposphere.elasticloadbalancingv2.TargetGroup'>: WebTG.TargetGroupAttributes is <class 'troposphere.elasticloadbalancingv2.TargetGroupAttribute'>, expected [<class 'troposphere.elasticloadbalancingv2.TargetGroupAttribute'>]
```

Relevant code:

```
import troposphere.elasticloadbalancingv2 as elb

target_group = t.add_resource(elb.TargetGroup(
    "WebTG",
    HealthCheckIntervalSeconds="15",
    HealthCheckProtocol="HTTP",
    HealthCheckTimeoutSeconds="5",
    HealthyThresholdCount="2",
    UnhealthyThresholdCount="3",
    HealthCheckPath="/check",
    Matcher=elb.Matcher(
        HttpCode="200"),
    Name="Web-TG",
    Port=Ref(web_port),
    Protocol="HTTP",
    VpcId=Ref(vpc),
    TargetGroupAttributes=elb.TargetGroupAttribute(
        Key="deregistration_delay.timeout_seconds",
        Value="120"
    )
))

```

**Comment by markpeek** [comment]
Try putting it into a list:
```
TargetGroupAttributes=[elb.TargetGroupAttribute(
        Key="deregistration_delay.timeout_seconds",
        Value="120"
    )]
```

**Comment by gkrizek** [comment]
@markpeek  I didn't want it to be user error, but it was. Yes that worked.
