### ISSUE TITLE
Unable to add  RoutingRules to s3 bucket

### ISSUE THREAD

**Issue by slash316** [cloudtools/troposphere#779]
I'm trying to add a RoutingRule to an s3 bucket as follows :
```

t.add_resource(Bucket(
    "redirectbucket",
    WebsiteConfiguration=WebsiteConfiguration(
      RoutingRules=[
          RoutingRule(
              RedirectRule(
                  HostName="www.domain.com",
                  HttpRedirectCode="301",
                  Protocol="http",
                  ReplaceKeyPrefixWith="newfile"),
        )]
    ),
))
```

However it keeps giving me the following error when trying to execute :

```
Traceback (most recent call last):
  File "s3-redirect.py", line 19, in <module>
    ReplaceKeyPrefixWith="1yeartrial"),
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/troposphere/__init__.py", line 327, in __init__
    super(AWSProperty, self).__init__(title, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/troposphere/__init__.py", line 97, in __init__
    self.validate_title()
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/troposphere/__init__.py", line 218, in validate_title
    if not valid_names.match(self.title):
TypeError: expected string or buffer
```

Any ideas ?

Thanks,

**Comment by markpeek** [comment]
You likely need to reverse that order a bit putting the title with the resource and not the property:
```
t.add_resource("redirectbucket", Bucket(
    WebsiteConfiguration=WebsiteConfiguration(
      RoutingRules=[
          RoutingRule(
              RedirectRule(
                  HostName="www.domain.com",
                  HttpRedirectCode="301",
                  Protocol="http",
                  ReplaceKeyPrefixWith="newfile"),
        )]
    ),
))
```

**Comment by slash316** [comment]
@markpeek thanks for the quick response, still no joy i'm afraid.. exact same error.

**Comment by markpeek** [comment]
Doh! My response wasn't correct anyway...so much for quick responses! Try this instead (change is using RedirectRule=RedirectRule):
```
t.add_resource(Bucket(
    "redirectbucket",
    WebsiteConfiguration=WebsiteConfiguration(
      RoutingRules=[
          RoutingRule(
              RedirectRule=RedirectRule(
                  HostName="www.domain.com",
                  HttpRedirectCode="301",
                  Protocol="http",
                  ReplaceKeyPrefixWith="newfile"),
        )]
    ),
))
```

**Comment by slash316** [comment]
Thanks that worked.. Doh on my part for missing the obvious!!
